SYSTEM:
  NUM_GPUS: 4
  # MAX_MEMORY_IN_GB: 64

DATASET:
  CUSTOMIZED_DATASETS:
    - /home/sdiaoaa/pile_processed
  ID: pile_output

PRETRAIN:
  NUM_STEPS: 23000

TOKENIZER:
  NAME_OR_PATH: roberta-large
